#!/usr/bin/env python3
"""Run a TCNN architecture/HashGrid size sweep for the n2wos 2LMC experiments.

This script is intentionally post-processing oriented: it keeps the exact FCPW
CUDA geometry path unchanged, dumps one coupled m-step WoS sample set per seed,
and trains multiple tiny-cuda-nn cache architectures on the same dumped data.

The point of this sweep is not to find the best standalone neural-cache solver,
but to find the smallest cache that gives a useful coupled residual W-C_m for
2LMC.  NC-only and NC+2LMC have different quality requirements.
"""
from __future__ import annotations

import argparse
import copy
import json
import pathlib
import shlex
import subprocess
import sys
from typing import Any, Dict, List


ARCHITECTURES: Dict[str, Dict[str, Any]] = {
    # Very small hash table and MLP.  Useful to test whether 2LMC tolerates a
    # deliberately crude cache.
    "nano": {
        "n_levels": 4,
        "n_features_per_level": 2,
        "log2_hashmap_size": 12,
        "base_resolution": 8,
        "per_level_scale": 1.8,
        "n_neurons": 16,
        "n_hidden_layers": 1,
    },
    "tiny": {
        "n_levels": 6,
        "n_features_per_level": 2,
        "log2_hashmap_size": 12,
        "base_resolution": 8,
        "per_level_scale": 1.65,
        "n_neurons": 16,
        "n_hidden_layers": 1,
    },
    "small": {
        "n_levels": 8,
        "n_features_per_level": 2,
        "log2_hashmap_size": 13,
        "base_resolution": 8,
        "per_level_scale": 1.55,
        "n_neurons": 16,
        "n_hidden_layers": 1,
    },
    "medium": {
        "n_levels": 10,
        "n_features_per_level": 2,
        "log2_hashmap_size": 14,
        "base_resolution": 8,
        "per_level_scale": 1.50,
        "n_neurons": 32,
        "n_hidden_layers": 2,
    },
    # This matches the previous cache_hashgrid_small.json scale closely.
    "baseline": {
        "n_levels": 12,
        "n_features_per_level": 2,
        "log2_hashmap_size": 17,
        "base_resolution": 8,
        "per_level_scale": 1.45,
        "n_neurons": 32,
        "n_hidden_layers": 2,
    },
}


def parse_int_list(text: str) -> List[int]:
    vals: List[int] = []
    for part in text.replace(",", " ").split():
        if part.strip():
            vals.append(int(part))
    if not vals:
        raise argparse.ArgumentTypeError("empty integer list")
    return vals


def parse_str_list(text: str) -> List[str]:
    vals = [p.strip() for p in text.replace(",", " ").split() if p.strip()]
    if not vals:
        raise argparse.ArgumentTypeError("empty string list")
    unknown = [v for v in vals if v not in ARCHITECTURES]
    if unknown:
        raise argparse.ArgumentTypeError(
            f"unknown architectures {unknown}; choices: {sorted(ARCHITECTURES)}"
        )
    return vals


def load_json(path: pathlib.Path) -> Dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: pathlib.Path, data: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def make_config(base: Dict[str, Any], arch_name: str, spec: Dict[str, Any]) -> Dict[str, Any]:
    cfg = copy.deepcopy(base)
    cfg["architecture_name"] = arch_name
    cfg["architecture_sweep_spec"] = copy.deepcopy(spec)
    cfg.setdefault("description", "")
    cfg["description"] = (
        f"Architecture sweep config '{arch_name}'. "
        "Generated by scripts/run_tcnn_arch_sweep.py. "
        + str(cfg["description"])
    ).strip()

    enc = cfg.setdefault("encoding", {})
    enc["otype"] = "HashGrid"
    enc["n_levels"] = int(spec["n_levels"])
    enc["n_features_per_level"] = int(spec["n_features_per_level"])
    enc["log2_hashmap_size"] = int(spec["log2_hashmap_size"])
    enc["base_resolution"] = int(spec["base_resolution"])
    enc["per_level_scale"] = float(spec["per_level_scale"])
    enc.setdefault("interpolation", "Linear")

    net = cfg.setdefault("network", {})
    net["otype"] = "FullyFusedMLP"
    net.setdefault("activation", "ReLU")
    net.setdefault("output_activation", "None")
    net["n_neurons"] = int(spec["n_neurons"])
    net["n_hidden_layers"] = int(spec["n_hidden_layers"])

    fallback = cfg.setdefault("fallback_network_for_low_arch", {})
    fallback["otype"] = "CutlassMLP"
    fallback["activation"] = net.get("activation", "ReLU")
    fallback["output_activation"] = net.get("output_activation", "None")
    fallback["n_neurons"] = int(spec["n_neurons"])
    fallback["n_hidden_layers"] = int(spec["n_hidden_layers"])
    return cfg


def run(cmd: List[str], log_path: pathlib.Path, dry_run: bool = False) -> None:
    log_path.parent.mkdir(parents=True, exist_ok=True)
    print("$ " + " ".join(shlex.quote(c) for c in cmd), flush=True)
    if dry_run:
        return
    with log_path.open("w", encoding="utf-8") as f:
        proc = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
        f.write(proc.stdout)
        print(proc.stdout, end="")
        if proc.returncode != 0:
            raise SystemExit(f"command failed with exit code {proc.returncode}; see {log_path}")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--build-dir", type=pathlib.Path, default=pathlib.Path("build-release-gpu"))
    ap.add_argument("--backend", default="cuda")
    ap.add_argument("--m", type=int, default=8)
    ap.add_argument("--seeds", type=parse_int_list, default=parse_int_list("12345,22345,32345"))
    ap.add_argument("--architectures", type=parse_str_list, default=parse_str_list("nano,tiny,small,medium,baseline"))
    ap.add_argument("--steps-list", type=parse_int_list, default=parse_int_list("100,500,2000"))
    ap.add_argument("--n-pure", type=int, default=65536)
    ap.add_argument("--n-coarse", type=int, default=65536)
    ap.add_argument("--n-residual", type=int, default=65536)
    ap.add_argument("--max-steps", type=int, default=512)
    ap.add_argument("--warmup-queries", type=int, default=65536)
    ap.add_argument("--eps", type=float, default=1.0e-4)
    ap.add_argument("--safety", type=float, default=0.99)
    ap.add_argument("--base-config", type=pathlib.Path, default=pathlib.Path("configs/cache_hashgrid_small.json"))
    ap.add_argument("--outdir", type=pathlib.Path, default=pathlib.Path("results/final_tcnn_arch_m8"))
    ap.add_argument("--python", default=sys.executable)
    ap.add_argument("--train-script", type=pathlib.Path, default=pathlib.Path("scripts/train_eval_tcnn_2lmc.py"))
    ap.add_argument("--batch-size", type=int, default=131072)
    ap.add_argument("--eval-batch-size", type=int, default=262144)
    ap.add_argument("--timing-repeats", type=int, default=10)
    ap.add_argument("--lr", type=float, default=1.0e-2)
    ap.add_argument("--skip-existing", action="store_true")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    exe = args.build_dir / "native" / "n2wos_eval_2lmc"
    if not args.dry_run and not exe.exists():
        raise SystemExit(f"missing executable: {exe}")
    if not args.dry_run and not args.base_config.exists():
        raise SystemExit(f"missing base config: {args.base_config}")

    base_cfg = load_json(args.base_config) if args.base_config.exists() else {}
    config_dir = args.outdir / "configs"
    arch_config_paths: Dict[str, pathlib.Path] = {}
    for arch in args.architectures:
        cfg = make_config(base_cfg, arch, ARCHITECTURES[arch])
        cfg_path = config_dir / f"cache_{arch}.json"
        if not args.dry_run:
            write_json(cfg_path, cfg)
        arch_config_paths[arch] = cfg_path

    manifest: Dict[str, Any] = {
        "program": "run_tcnn_arch_sweep",
        "backend": args.backend,
        "m": args.m,
        "seeds": args.seeds,
        "architectures": args.architectures,
        "steps_list": args.steps_list,
        "arch_specs": {a: ARCHITECTURES[a] for a in args.architectures},
        "runs": [],
    }

    for seed in args.seeds:
        seed_dir = args.outdir / f"seed_{seed}"
        seed_dir.mkdir(parents=True, exist_ok=True)
        base_json = seed_dir / f"2lmc_m{args.m}_dumpbase.json"
        samples_csv = seed_dir / f"2lmc_m{args.m}_samples.csv"
        base_log = seed_dir / f"2lmc_m{args.m}_dumpbase.log"

        if not (args.skip_existing and base_json.exists() and samples_csv.exists()):
            run([
                str(exe),
                "--backend", args.backend,
                "--cache", "exact",
                "--m", str(args.m),
                "--n-pure", str(args.n_pure),
                "--n-coarse", str(args.n_coarse),
                "--n-residual", str(args.n_residual),
                "--max-steps", str(args.max_steps),
                "--warmup-queries", str(args.warmup_queries),
                "--eps", str(args.eps),
                "--safety", str(args.safety),
                "--seed", str(seed),
                "--json", str(base_json),
                "--dump-samples", str(samples_csv),
            ], base_log, args.dry_run)

        for arch in args.architectures:
            arch_dir = seed_dir / f"arch_{arch}"
            arch_dir.mkdir(parents=True, exist_ok=True)
            cfg_path = arch_config_paths[arch]
            for steps in args.steps_list:
                out_json = arch_dir / f"tcnn_steps_{steps}.json"
                ckpt = arch_dir / f"tcnn_steps_{steps}.pt"
                log = arch_dir / f"tcnn_steps_{steps}.log"
                # Make training reproducible but distinct for each combination.
                train_seed = seed * 1000003 + steps * 9176 + sum(ord(c) for c in arch)
                if not (args.skip_existing and out_json.exists()):
                    run([
                        args.python,
                        str(args.train_script),
                        "--config", str(cfg_path),
                        "--base-json", str(base_json),
                        "--samples", str(samples_csv),
                        "--out", str(out_json),
                        "--checkpoint", str(ckpt),
                        "--steps", str(steps),
                        "--batch-size", str(args.batch_size),
                        "--eval-batch-size", str(args.eval_batch_size),
                        "--timing-repeats", str(args.timing_repeats),
                        "--lr", str(args.lr),
                        "--seed", str(train_seed),
                    ], log, args.dry_run)

                manifest["runs"].append({
                    "seed": seed,
                    "architecture": arch,
                    "steps": steps,
                    "config": str(cfg_path),
                    "base_json": str(base_json),
                    "samples_csv": str(samples_csv),
                    "result_json": str(out_json),
                    "log": str(log),
                })

    args.outdir.mkdir(parents=True, exist_ok=True)
    manifest_path = args.outdir / "manifest.json"
    if not args.dry_run:
        write_json(manifest_path, manifest)
    print(f"wrote {manifest_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
